name: delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  google_maps_flutter: ^2.13.1
  url_launcher: ^6.3.2
  geolocator: ^10.1.0
  shared_preferences: ^2.5.3
  signature: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
